apiVersion: v2
name: amd-gpu
description: HAMi AMD device plugin for fractional GPU allocation on Kubernetes
type: application
home: https://github.com/Project-HAMi/amd-device-plugin
sources:
  - https://github.com/Project-HAMi/amd-device-plugin
icon: https://raw.githubusercontent.com/Project-HAMi/amd-device-plugin/main/helm/logo.png
maintainers:
  - name: Project-HAMi maintainers
    url: https://github.com/Project-HAMi
keywords:
  - kubernetes
  - cluster
  - hardware
  - gpu

kubeVersion: ">= 1.18.0-0"
version: 0.0.1
appVersion: "0.0.1"
