apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "amd-gpu.fullname" . }}-device-plugin
  labels:
    {{- include "amd-gpu.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "amd-gpu.fullname" . }}-device-plugin
  labels:
    {{- include "amd-gpu.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "amd-gpu.fullname" . }}-device-plugin
subjects:
  - kind: ServiceAccount
    name: {{ include "amd-gpu.devicePluginServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
